name: 'jaffle_shop'
version: '1.0.0'

profile: 'jaffle_shop'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  jaffle_shop:
    staging:
      +schema: staging
      +materialized: view
    mart:
      +schema: mart
      +materialized: table
      # +docs:
        # node_color: 'silver'
    # +docs:
      # node_color: 'gold'

flags:
  use_materialization_v2: True  # Use the new databricks behaviour